### ISSUE TITLE
Pretrained Model Weights

### ISSUE THREAD

**Issue by jyunlee** [PengfeiRen96/DIR#2]
Hello, thank you for your inspiring work! :)
Could you also share the model weights used for your experiments in the paper?

**Comment by walsvid** [comment]
Thank you for your interest in our work, we expect to release the pre-trained weights in October.

**Comment by PengfeiRen96** [comment]
Hello, we have released the pre-trained model  :)

**Comment by jyunlee** [comment]
Thank you for sharing the model! Hope you have a great day! :D
