### ISSUE TITLE
pixel joint mean error and joint mean error

### ISSUE THREAD

**Issue by xungeer29** [PengfeiRen96/DIR#5]
DIR:
```
joint mean error:
    left: 10.74602734297514 mm, right: 9.60523635149002 mm
    all: 10.17563184723258 mm
vert mean error:
    left: 10.49137581139803 mm, right: 9.40467044711113 mm
    all: 9.94802312925458 mm
pixel joint mean error:
    left: 6.332123279571533 mm, right: 5.808280944824219 mm
    all: 6.070201873779297 mm
pixel vert mean error:
    left: 6.235969543457031 mm, right: 5.725381851196289 mm
    all: 5.98067569732666 mm
root error: 28.983158990740776 mm
```
IntagHand:
```
joint mean error:
    left: 8.93425289541483 mm, right: 8.663229644298553 mm
    all: 8.798741269856691 mm
vert mean error:
    left: 9.173248894512653 mm, right: 8.890160359442234 mm
    all: 9.031704626977444 mm
```
![image](https://github.com/PengfeiRen96/DIR/assets/32890569/9c444104-e007-4b8c-9037-4ef4d1aad919)
`pixel vert mean error` and `pixel joint mean error` is pixel error in 2D space, maybe the MPJPE and MPVPE in the table 2 of DIR paper should are 10.175 and 9.9480.
This is just my personal opinion, please correct me if there are any mistakes.

**Comment by walsvid** [comment]
Firstly, the pixel vert mean error is the MIAA metric mentioned in the paper. Secondly, for comparisons regarding MPJPE and MPVPE, please refer to our ICCV camera-ready version of the paper or the latest version on arXiv, and pay attention to Section 4.5 in the paper about the impact of different alignment methods on the results. Our results surpass those of the baseline methods and are reproducible. If there are any issues, feel free to reopen the issue.
